package com.huge.ihos.search.dao;

import static org.junit.Assert.assertNotNull;

import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import org.springframework.test.annotation.ExpectedException;

import com.huge.dao.BaseDaoTestCase;
import com.huge.ihos.system.reportManager.search.dao.SearchDao;
import com.huge.ihos.system.reportManager.search.model.Search;

public class SearchDaoTest
    extends BaseDaoTestCase {
    @Autowired
    private SearchDao searchDao;

    @Test
    @ExpectedException( DataAccessException.class )
    public void testAddAndRemoveSearch() {
        Search search = new Search();

        // enter all required fields
        search.setDs( "RsVaKzWlJnJq" );
        search.setEntityName( "CwOlRlScMeQgLnVoWbZfOxBdNqHiPyGxHyBzFsTgTlBbL" );
        search.setFormAction( "CkWwCoXcCaApYaLpFyIoDtKkDjGpYuRqWxTmTdYbFrShZtOsXhVwHmVvPiXbJlLsPjRkEnSbIdTgVhWkLmZtMfFwGvPeLbQvKhAjQxCoCgXfWeCzNkZxYnXqGpZwXsJhCrUlSdVfBaCbMsPuEvYkWk" );
        search.setFormName( "XuBfEjXwXcPvPqDfAlRoVhHjVpPiJuXkUpVjCqQnIbRyTwNtEc" );
        search.setGroupBy( "FeOvZeUaWzFmKwJoBtFlZfDxWkRyNhCpBtMtYoGpEsSwN" );
        search.setMyKey( "RiXlBcCvLiXyUsCjFjGiGkSaGnRaRtZvYgNfEbDdJrLaR" );
        search.setMysql( "ApGjVpRwHdHtHxBwMxZcTfJrWkRpKaQfRmMrMmEuKgLrVuOeBhXkZyNpCnXnRpOoFxJgOvVuHpCqJnBjTzTfJtPiHgVkVxZoFhWiXbYuTqPdTcEsGhUeMiFzSlNkShDaHdAbMoAsZxXaGrPqEwVzMnAuDbQdZpYwHvVxIqSnCvTvXcSmXoMxGlKxBmFaAmAsSuRvNhHtAsGrUyYvTyGkKkFiYdTpAuWtKuGjQrZzHtKgRiTxAmGtDpHfAfPfDjKrKsReHrVuKqGyBmSfWpPiJjMhZwLwBzSaIhBqWmUtIgVrBiVnWkYwJrRqGiDjXoWuNhSyVvCyGnXhDeFzEfFzIpKsEtWuArMeAzPeXgNmLpLyMzWqXtNdJjImVuLbLhUrIoYxSnMjSlPcBrWyMjQpVpIzVtUwJpShPgDsRnXqSiCdTqSxRjIwRkKeKyWtXkRfFiTjXfPuWzKfSsTcPzEeElOrUgRpFqWnHmCvVzSfEoRcAeJbVjPlXoXdYvSiPuRhQmVwOfRgQiNrReUfHqDdAyBwFhInDfOvCbSrVxCeQdIfQgOmVpXwPuYhSbSxOeYiVzWuAyBsTnSiGgFsIlIvLrOdMuBmCjIoAnEnQeUkRtBzAjAxAqIqBpGqEiOjWqZbWbUcSaKtOlRoHpCcBiKjWfDaBqIpJwOfSxDpVjXdKbWsQeXcKwEcOaQeWgBeGlDcNmDvBlKfZcLvCnRtSjHfXhPsNuCrJmJaNrGoJdYqOzLgXkJlSwFkUvGgJtUuAoArFnOzIrYuKuXkIdSoYpQsGbWuJoCcQxRnLaJhQeMaErJmZiSrFkAyDpDmBaImFlUgWhIxPyNvRdAbAnZoZnFbRyJsArJhSgUnUyAlElKrTwQdWoXoNpOeMdMfHvTbEkRdVtKgSfUuUkJnGuOnMyEqVdMqNmPmDwRiJmWeShLeZvZhEpCkSbLeAgEgZrAjRtHfTaFkAmWdCpLmJjKtJjStFpYzUcPgEuNtEuDtApMsQsKfZoXwCfKgHgCpTuJyTzFpOjVeLyUsYlGyNbQqTcGnBeEeClQjVqZqOjXhXcAuRpJwXsTlCfTtYwRySmSvRsDgHnMnHaVsRwMyYgZiXgYdHuVeJsXhTzTkUdOgYhNbWrKqYkMkGiPoUnAmMdBcSdLoBrVfGrBcPwBiQdCmDeDvIsAgWcXwEjVyFqHhOuXuZiMwHiOcDwMxRnRmYnZoFzQfXtOkFiOhVwNhFrErRiQmBmXpDjUzSnYcCgHuWhWnNmIvIqQyCnRwGdTwHtYjJtPqUpRjEjAzFtLdByElNpEcTiYwWsWgJmBiMgLnNyJwOpXyNbVuJlNdDrMcVsPtDwEuKyXcFzYoGcTtZeFnPlWqYcMcAcYsKvRlFyLkSjYbZuSvKdFuVlZrNvMpYyOpIuLsCuCyJmIyWeGmIyEvGbPsIoXdLfThGrIfSzLzAwEoXfMqGhEaZcXgHuKoYyIeGeDiUkSlLkTfPjYpTkVyOkIbSnGjWxLrJcWbWkHgJnDyAxDaGeXzVwOgYfCnDiCtTdDyZpErDsZfEdMeBjNuYoSgWyQjAcTxGyApDsAfUkRfHgPmGmPkVkYfGrCaLxZgEfVzMtFgUxKdSfPlJjJiJtFnMdKqFaRyGiPmFgGpPsYuWxZhTlEzSoGqNoCiQyIxCuKrKbJrEdHkLsKsTzTgVmVeBxWbLmSmNnDxDdNlZzSxZbBzRuKsLoGkDiGbXeLxLxMpCrJfToGcQmYyIzTnTvFmTtLwGuIkWhDhBoVwEcWlZpSzMaMzDiRqVuQsDdPcFsJmZwNlGfSuNyMiAhMdMlGbKxGxQeKrUyObEwWpGqTnAfEmWmHuZjQhFzSoLfSqOoKtPcCxSjHaIoXcPlOqKvLuHrIrZrMtEnCbRuRrXxMdFpQwVmZtCdCuZpOeJtSoLzQfGkWvJrDdXvGzLlLbVkGjEjHrXnIkMaTmRnSeRaQvJnOlMpHnLcFsSaNaPiVoUcVsGeGsPdKvZlZaQdYfWtQxEqLiFfKlHkEhZyPsMiJhWdCdZrVqRyRlTkKgAvEnJqHwMsZcTpRuTlOfSfLpJqFrOpLkSpYbPxZaDrHhViXgTaKdLcTaHqHvCbYfMsXiMaZpPeKbCnGlYlOcOnPbSiZsWxOuIcTwLaIlIiNvNwBsMiHnVxXrEsGsKjHhUzYiCtZuTqWzUlSpTuJkLbLfXrKoOzBfTyJgWxFdFsKuRjOcXaHwYwKkUkNwVaIjQlDeRhZcOnDdRyFzQnNvVfYkIfDsEdVsPeOfZgWcTuMyPyIlCzJbCwZkApKkXhBrJzRkClRlYoWlEzZzGwYnHaKdTkEoZuLmAxRxQrEpLbOaSnClIdFvKtIyXjTnMyDeCmRzLjBtFyXbJuOkNcOyMbVwDuJuEnWjYkBkNtDqToRgJcTvZqNkGsRaVsMdQsEpKeMeEvXpUqTzSiLxFuPiZwLnPbVhMiSrRhPiWeFtNbXcWuReKcQfPkZaEcApRdDrKqYbThHuDhZvBfGwGaAlEyXhJhImIrSsBuXiRzVoKhKzIaDmWqTnNyMjLhQgTyUfOcBgQcSfTqQkLzIwFmYfFzVhPcShOtAmEqVcFpOlEzDsOtWyKaLdMjBdYsUgDbDkPnFlIqUfAnOiFeBmOrAlYaFaItHsLqTjKnYqHdUhJcCmYmFkUzByYmSuVoSzWySqMuSgCmMmDcZwRrGwKaTiSmUiHiEgOiItEbVeXlZzFaRfNoUgLeBrJfTuBwQxTmDfFuArYmQrYxTjDpOmKaEgKnNsBzWyQaVqCyMtJgDfToHjShUuFmLoGrNiEvIdFkKwVqHwPdFxAeTaUqZoQkZlGaVhRxNtOeOlQgWvYlDcLhNoEzFhMcFwUiNtFuLeIhImFvVvFmXqIvKoScDbRjBmSvEiSrJgHuFnCmCzZcFtIpTgYjRfXsTsAeYpUnXkOuZuEjGxOjHcItDvOgSbHqUcOyKuEgElQlNuQqApUqIbTwIjEkIdKpDrNzDvSgIzWrByDxEqRsOfUwLnQgXnMrRvOnDfHgNdGmMpAqPlLeOhJqGyCsTkBxUiOfVuEaNgJeHgEbNfWlQaTjUsUlVaJtNnMhDfPbKyOgYcQfFlSkOqBtIwVsXrXsOaSkUvNqSnLzUuXgUiRwRjJuOqGlVfBgXgCjWdRzMpPbUfHdFdDxYdSnTkLnXoCeJoZfXvBxCuOlRaKfRsRqOsVhTjPiZrOtRqVsTuFkPxZpNyFnEoPhQaIwLzSlFmOsOuQrZwGvEgEuFoBxIuNdErHpHhQvOlSbGwZdOcUyBfUwOhZtLtPiJrTnKsGxDcAfFgCfTbIsGbSeIsMsWkRjXqVjKyHkFuCpBbLnArUqDbLnTxHuLmXeZyRdEfBtDaVdSvYwPzHhRwIxChNsPlLhAmEiCqNmQrXkXbNxYnJaLzPwSoAjDyOjAeLkIcTgJqZqYmQmToYaKsZpAaAtSlVxAhVhOaInTrWiNcDsWuIlJbEbDyZyKeTfWpCiStJiZnYuZwOvVlQbIjFiLkTnLhMnDxWkKvMhIiDfUjKwIgCyKoDjMgYbLcVsJaGhYxEvQgQsFxXuEzGoSfCtDjMyOxOtQpUhImMxEdHyGtUxHbMuRpLdBzOkFuAwEpUfVjSnSzEsWqPlGoZsNxEiKtSaTwRrJtOgJvPaSyDvMnXhQjRfExWeQkEzUmLtCkEsSqQfZeYlMqDhCoNaBwJjUfOgEbSfAoKjHrQaIqOlMuJjKcEyKkDrUhShVwBuOdYkYnQdTfMcGwNjTuRjZbThHpUrOiWaQpUqDnWfRaQcFmUsKkQcOsOoIqSlZdNuBrWuGxHxMbHpIeFnNfKgCpQvTwSaYeMvYmFeJgYuHcIuUqSbKmUnZeCoOfEiDhAbLvUpChBtBwUoKcAhPqTuOnLyMqYyWkWlUrGjQsWgVdOlAjJsTeLtTbHiZhLuCaItKaMwGnDpHsIsCmYkGiRbHgLhLrMzWsLbOxMbWjTkNaYzUiUnOqFkUqArLgCvTfPwWuQgZjKkEhWvEaCsKtYeLjXcRxObUkIhOaDoUaWmQzXrNnMcKxOdOoOqQhXpOuIlLrRxPiGbNjDbEaSjYbEkThVpXuLfKbPjNoIaLlOkSjIaLuOaItRwFpJuMcTtCeEuSpUxWdOtErIxTbYbDyQkBwXxQaOeOfVkVjTkIzZyGeUeCoMwRdIyFiCfPjKmDaBmTvSfIlPbKlEqYpVdBbChMaKjWhCeSvIjAkSuDiDsVtBxUmAlEaVjQtLsQqQrLzUqMjRzToWbObRcTsDrBzWvBnEqHwHjKfVhHfWjWbVoTmLuVdEaNvZtNaAdQvZfVcFdCsJoNaDoEtFfOqIwZpRrCnLwUfZsLoLoRsHtLiMoEiIoCqDiRjVtMyKgRyQwWuBoMpTuDgDeOfGwIlLvVxLkLfSvUuRlPmRwSuKbYnZeWpGxKgAvKfSyUuUbZrKsBfToNnBbLjSpCiKhGvZcYpJsBoScSnNaVyDoPxRaDaSmHrVzVeYwOpEeCxFaLdScIcJxRjOpGnPoTsGaAqXpMuTpJzJfIpAgPqPqUySgXqMiFkQjGaWtNyRrTiFbDnFyLjPqGiPlNyGgLmHdFmJwYoVnPuQvHcFqPuYaIrCiLmGkAbBeRsMyPmVcZlTuOqCvLtPhVeOrXgYfJwUnUoWcIuWnGdHuKmGkVuVpFlIyAlFnDsFmOvEhNzYxRuIrDtRcAlYaShNrFjNtOxUuLfVmWpXjOmDlAqPoEwVnXxSdYbQpLeZcKoVaSmEhNkQePaJdWvKtIbKePzJuDyVqBnWfCeQtVhPrObRjVsIhPqGiKzTaTlRcCfWdTsLlKvPxKiTlDbBfPoUiEjIjWmCyAeLtNjNmTtVcWxBdNdGuVtMpPqSrBjFsDuBhVaCuCpIuCyGtWvAkJlUdJxNmIvDwSuWwVjLnAiNgOjDoDtCtQrPsEbKaBmVpJwLeCvCxGtVfTzFhJuLkVgZhFvJmSnWcXxDwLgWgOmVrNnCyAoWoEpCmSjLnOl" );
        search.setOrderBy( "AzCcGoCjTzEvEfKhRyQmJuViJpYvLcThLyBmYtXvMnBiH" );
        search.setPageSize( 20l );
        search.setSearchName( "HvYgLuYpXkXrEmCmTwOuQvVlCjSsZfDoKzMfSxQqMjFyFtIpOm" );
        search.setTitle( "CnZmNjDeHzGhVuKzEeWgXmHbCjBuBlWuGwRwOhRqVpEzHzWdYqEzYsJcYoReRaTwFxWtNoBgMbKsKfWj" );

        log.debug( "adding search..." );
        search = searchDao.save( search );

        search = searchDao.get( search.getSearchId() );

        assertNotNull( search.getSearchId() );

        log.debug( "removing search..." );

        searchDao.remove( search.getSearchId() );

        // should throw DataAccessException 
        searchDao.get( search.getSearchId() );
    }
}