package com.huge.ihos.search.webapp.action;

import org.junit.Test;

import com.huge.webapp.action.BaseActionTestCase;

public class SearchActionTest
    extends BaseActionTestCase {
    /*    private SearchAction action;
     @Autowired
     private CompassGps compassGps;

     @Before
     public void onSetUp() {
     super.onSetUp();
     compassGps.index();

     action = new SearchAction();
     SearchManager searchManager = (SearchManager) applicationContext.getBean("searchManager");
     action.setSearchManager(searchManager);

     // add a test search to the database
     Search search = new Search();

     // enter all required fields
     search.setDs("LiCnBjSgPjPb");
     search.setEntityName("GpAzBlLwOgSiJoQpYaFlIvUaKvXbZgIeEcDgKjRtQxWrG");
     search.setFormAction("BdMfGvCcRrPmBbGaJmOiPzXhAcEzXcSgGeNeYqSuKtWlRdChSiIeMzPbMoTcOrUcSmBiVtEyTtGaZhVnPhYfQzWbUwUzHeZrZiWvIqBtLxBfIcJkZqSaYdZjLpUvOmIpKzCtOyExPzOsFaFuAkFwBg");
     search.setFormName("DrOqLqTxGrGbMtRiHnFrPcGeLvBmAgKjZiSeRhOkJcIiOwPrEr");
     search.setGroupBy("YgGqYjEqMbXcHnCxOwYwPiMlNtMtSmDlZeReVfFeFgZtN");
     search.setMyKey("XeOiKtFzHuDvTaWeOgEoKoFyUwCdXgTbZbEuBrRpEmIpU");
     search.setMysql("JdZaKzHrKkOfBkCyKdAgFiGuKcGpJoXaXuXjInXyHeZrSpWoUvXuJsFkXfImYeFkRmBxUxKkVrTuMxKaXoApMtTaGcLwPsLwHrFoHdGnLwEyKbPkOrLsAoOrJaPfElEbDdBqTlVfUaTbGtZyYiQuFzXkZkLmPpXtSwUbScGsLhIsRcVeRcYxXzHnHdVbAhZhJdBwLmLdXtGeCrNwTpCrIiVuEeNiYcMmDyXtUeItUkPbHhApNoRlKlIlJfLzWsGjYnKeQsGdJsBzTlVhDxKyFlHzGwSjVyOwYdYiIzZyEeQoYaXdQjGaOsJiNvJyOvVwGiGtQrNqZhAsXxEsIcTtXkZmMjDiQdIkTdPuOeLpCrAaEbYnIsAqSiFaAjJkDyOiIwXvBeIkWpYpXaWiEmQhRaZgScLmCuUxGrOeDnSnEkVbEiVnZxSeQhHeDoJeXrNzVyDqAcXzQtNqUiMqSgPqGuCeLcJcCpPeIjReXeIqRjYuXhRmRpMfJsZrFfCaGfKkZtUvRvAkBwAaIuKcIfLfLfJyOkWgNuEqRwMwZtMvPdKqUcSeFuPnCoZmNsFfRkXaJjYgNhNyDjScRdDuLiRoExKlMaSkHiEaBhQgOoRkQeYpSoJeAbSsZbXgEzYiMwIaYpPnWdOrVbCtJyUbQrZvNsTqTcWbGdZaWcEbTrWuWxFkXnYvXuIaItMwAuIsWiStXkUuEyDdFeLfIwLhKqNsJxMdFdWmYdAxGjCgQdDjXvKtXyXqIeDyErBhQqSlVnLpNuHjRgKaDuCqQqMjDcKxKjJuWeFhQmFfYzRuCaYwSsMfKaGaVnNuKoYaBhErYnPlEeRgHvFwGuAyPkFmYnCuErJnPvVfGuIlErVfSvMfJwSuDhBcIhWkOxZyVqVmIxIlGmCyTtIpZaBcLtZsReUbThEuGpLnCbMoOgPkSjHzFcXnWzScUiBvWdSuWyHjPvGsVhJaFrZhGpNfJaVrShVnWsLiPvYyBbMyCvOcUbKkPyBiGyLgIaUyXyZaIaCeSfXwYxQxMwHsNwIvLeViAeEoPrFvZbWfFlFqXwErDbZpUyNlSzRhXkBdUcGfRkEjXwDtDrOhPjMfRsQwLiIiWjSyMgKpNdTrXuClIhFsHlPpBqQgJyKcIiMxXyYzImBcQrOdSbXaZhNaYqGbVqQaWvRjFzFcUfOzQwLfRvGrYgQrGtWvZuUoHrVrXjBkTpLoKwWeGuTsEvLhSzUrPlExWcDhVdKtWdDvWtYsFzWqAxUiBlMpUyFxZkHfLaIxIgPsSyFjXyEgXkPkNyKhGqDgUlHiGuXoDlMlCzYfBjGvNzJsQjVcNfBtHvXlJlWqGjScXzUyBiIpXzIxAwZhQqOzPyZcNzArHpGlRtYeCqNkItShSwQnDeXiMsEcIfImKfGeGtDtFkDmTbEzRmPpXrBaFvZwPxXdFbFgOyCvVwEyFaSqJdRlWeWnJjCjZdMiHtPkPyKqDnMxXxLfXsXiJtCfIkPcCaBoTnOaPnIyJnLiVnBbAkYkEnGgVzXlNlQbZtClOgAjNeTxOrJfUgQkMbHvNjUfLiPrWdHcAlBjFuSfKyVbGxEqKtTjDoIjAvXaYwVgCkZdZyGeNqUdFlXhPwAhUxUfRgVaHkTtPxKvJqYrSdQgTkFtZoZaNfAoZrTrAxRiSrDgAyMrDgJrMmRnBzSvYxOiIeKtRqYtOoRlBxBcFfHxHzKfDdToJkXkLfFjHxCrGqUvUqPlEjCjKsBoAoFcBaXqJhZcGyWfHqSlPpKnOtCoNiDfWiOeVvRdTsPxYiDiUpBkDgXdWjSkHpWgInHuRwGvBvMaYjDaLzKvOyBmUaGuZaAgWrBiYtEiOmQfIeEaLrCpLxFoOhZiOyZoLpZkOgSuZkNcEfFqTmAzLrIsGxGrVnKtIqHrNhUnVhXbPeCwOwVuPqErWcFoYeQhJpBxSfTfUwXySzUsZxOkQzCqHkIrAjWqCtHoYgVzLgMoYzWyHjBsTqTvMrQfGhAoOiHgEfLiFqXxTrItVgFjJuHcHkVeYhMhEvHtDnAjKdZzHhUbTnAgKkRuAdVpGdNrVbCcAjYoXxTuQyLtSxXkPbFbPfQeOpJwCyIbNfUhPoGkDwZiUfTxEzRfZvDaRnFrEiRpEmWcLrXoYcEvWsMfWoAhLjOvAzWcLxMzVrUzRxQhTaWwZvNqVxCfSrXgBmFzUnPuLiQsDyTwEnNzDeEeHmBuScUiYxGaXzKkBuEaBwNcTjKkJoFkAoGfFeGlQgEcYqEoGsCgYwSsWpUrXpBxJfItAfFiZtXnHmQhKdDzUeNcGjRaRjUuJfQoCoZmHnPdWpVaSrRjMaTgKyDmAhOfBsVbMmYtZxUaGqBcBzGaMcCyQdBsUkMuHjPcOdNzMrHuPnMiKoWdUhVhXpTsPsNmMqAwSsOjRxVcHvIvGqWpClUhNwYbCxPjWnRuBdWpBtSnCsBiKjUuHkHzEeIeCmBjXjHnQsSmSrMhQuEjClPcAqUmOwWaDoMeVvVoOeGxFuMsWvTdCsIhUrGoQyRuCtOqRiFwPwJrQqXoDtYgLdPnXcFgPsBiNnGdKuAtChNaKwSxCdQxCbTbFoYxBbVeIhIoEdYeYwHfPuLbGoWhYsAbMfQjHlUlXpBdFtRzXyNfHhKtLpViEwBoPlFhUsQkJoAvOoXtFcLzKaDsVuQjTwNvPpHdErWyXmMsHwWpImJpOuYmYbBmFuHzCdZwHhDpTxUyVyUlZtIzKfAcBbRvPaNoCcSiNuWjYuAqUjWkNaCsWpKrYiBhXuDxSsMoJlYoUvZeRdImPaMbHgOrNaNjOkReQfAqHbTuEiLrDpQkQtWiUsYvCmVjAgDbHyTnVjPnMyLxJwKzHdXmDlByVqIqBkImSyIiYxDnLdEdShAjMbOyQwKeCwHmXgFsJgCwOwEtMiUnQpTuBqIrIkCqSfIvUoUsMeDcLvSqDuTpWqGmPsXnMxKbSjMlTpZpFaJjHqIeVnBzSbAxKnTvHkVtXqBjOsWlRtVmDwRvAlEnVnLcAwFeXwBwOmBmFbGkQpMcSgEdDvWlBbOjMgUpOmOyBqVoFjGzQrZpPmEyIzKyPpVgIlNtBaDoFmReMmKnUnUyDjFvEhByKxMrTeArOoZjOrFiMpVeAeTxSxQpOgScVnJjNfEnMfQiYsLxFaUsIvMmMzDgBaXdPjGqBmOpSoRfNiKtBhGaUwLsGdEaIdZeUaZcVtBvCvDhRnDqHeCqCwZnJnYsYiPtMyDaPiJfCsOiQiPuHjDjEbTyEhCkJuIsEdZqRyFuXeDaXoZlUaUqDvJsRzNjEsSnWyLzNeOnMpDcFvKxHwRmNtFtGnGyLuIqCiOrPvBwDjOlPyQjZjPiPpSiUbYdVgMoLuBcGvZdGhBvWlHtRfXsEvPdCjJdEdPpApDxEzYoCsCgBjYxDyTiNdQuHkAdApIgPyTqZpMdGoLnOlXvOcDiNiLqZxNqYrXtOtUrWoKdYtSuZfAqKkNvZmPmYrNnMfGtKhUlWlNpUaJqPxQcKbLwQiFaWrOwYaYlKmRtAjSfTnWkBvAcVrPgUyIfPtSwTlBsMdApXgFiJiDoGxWrBfYbNmZxFeOtXwLtJoIxPgDjHnClGpEeFaLaJkFzAxRfUuCwYkOxQtEjVfUiZsKnLqIkSvPkXsAdCzUjBxFmHcOwAbIqMbOyYfSbYfTsYxVjDyHwGxCtHzNwYuNjCtZzRpEsKdHuFvOtGoHyAwAfIyQiAiIyMfDhApUoBnYsXeGsQcXsEhFrNcQpSpAbWaPnWmKzDzYdPeBrJhOzMgFwJgKjSmCcXnLnWmAqWlRoAbAyOwRmQkYzMxGrYvYlHaWlZbQuXaNbTxFyUjBlHrFsKbNfByGhBcWzGzDwSdCmFtVnEtHeRfDjOsDcHjFtYcNlWuQeBzOhHtYlYxLiYlAjRaUkFoLwYzDvImVcGzEhStEnZyZaJhRuJoFoDfOgDlWhDrUeAxKgYdTjGyYlHxNlSsPlMoUwZdOqJpYzGtWwHtVdMvOmQpHxPnHbOgWvNjXmXrIoJhVyGhCxGqUxOqWbYqCjKyGwDsQaQhZuOsTxAxKnCwFpHyMtCqGlDtNpGiExYsWkRjHlMrXxEjOzHlYrWnZpKlBlQdJjNhPuYzHmFaLfYyRyTaHoMiKgZiYoShSoLyWsKaImStYoDyRrDpSpXjLlWwDaBgPjHyVhBjHuGrEyAkQbDmPeJgDfLeWiMqVcXuVhWcDjMkBdYvWfWzTsFqAsZcJhAqNvZoOxIsHtQjQhXfHeDfJyZtCyGeUuIoFoDfZeBnTiXcWlWdIzGhNfRnSnRjHdHoCeImBlVdArVsGiRgPxVnJfHuTsHeMpXyQzDtJiQnQkLuZpVxJaYdSbSwKxMgEaNgJfTiEnGaRzClDdXfUxPcIcTfRyNyFaYwBcWwOlUsYaZlKrZeTsIfYuJnLiNcQyIzXtCbZgTeOtNvQsNcSlDlJzJxYyWmGoWlGyJuWjCfApLvBlYgAkOmUeAlYqIxBtAhGhUeWuWbFkTqNkPaFdGsNjKyToDcImXdDqObUaPwUiAzBvLvZeLgOuKvDiToUbSdIqKvHbMbYmDjQsOrSoXfBjNqOvBrXqWxDuBiLuMlEqXdFtJyCgFlKtMhUpYdUwZaRmYbXlRiJcKhCwSgJzYgYmLyQpXrTaFjSlHtZkBsKaEzJsPnYbOqWiIzUsEwXcZdEhLyEiOfOuUvVnMsPxDmEdDhKgRkElTvPoGbYkXqPsUwXjXfMlNiGpBuIvVkHjGoDsZpQyJiRbRnZjCyPvYbGmKbZiWdNfSqJrJrTaImZeKwZjApOpJbBbVnKnFxWoQkXjSpJuFrEaUfDvQxNvPpMxAnKeJfOsOgTqPzZpRaLwLxCwImJrLmKmMyFnPgRnFyFlOwJoAxLeWhBsUsCgZqOuPzCqLjZfXgZfDiWjZsWwUbLfVzRlGpIiUcOkYfGtDtNmFaYlNgYwRtSvWyWjInVdJeJqPrQjNvLuMiTdCuNpUpIrEoLuFyHmChHf");
     search.setOrderBy("YnEbSzNvDlGfAzWeYkAuUqRzKrSeIeRwKvAyBoTxEyKwH");
     search.setPageSize(9.667836929822379E8L);
     search.setSearchName("MkEdMyKkArNsPzJkQzYcHdBjOlImOnKiKjEbAkToCgFuEeWpEo");
     search.setTitle("PhSmEwLbWrJiNbEeBxQzZjVlGwSpYxSqSfFeDmWnGnQrAsCsPoJoJhWbAyBvXwZxUjVxFaFhDqOwBfMd");

     searchManager.save(search);
     }

     @Test
     public void testGetAllSearches() throws Exception {
     assertEquals(action.list(), ActionSupport.SUCCESS);
     assertTrue(action.getSearches().size() >= 1);
     }

     @Test
     public void testSearch() throws Exception {
     action.setQ("*");
     assertEquals(action.list(), ActionSupport.SUCCESS);
     assertEquals(4, action.getSearches().size());
     }

     @Test
     public void testEdit() throws Exception {
     log.debug("testing edit...");
     action.setSearchId(-1L);
     assertNull(action.getSearch());
     assertEquals("success", action.edit());
     assertNotNull(action.getSearch());
     assertFalse(action.hasActionErrors());
     }

     @Test
     public void testSave() throws Exception {
     MockHttpServletRequest request = new MockHttpServletRequest();
     ServletActionContext.setRequest(request);
     action.setSearchId(-1L);
     assertEquals("success", action.edit());
     assertNotNull(action.getSearch());

     Search search = action.getSearch();
     // update required fields
     search.setDs("OtToNiKvCiSo");
     search.setEntityName("SfVlKpUvTuEcUgHjOzKaEcTvKlBxFsPfPhSxMmEhHiIvK");
     search.setFormAction("WnYlYmJbKqWzEcHjDtBtNyVrPjLiZzTdSrHzLbJhGiAvTwOgLqFlEtBaHbIbHdUwGwVnWpQuPaHhBkXvRiDiHbWdKiBuYaHsQrTkCiRvEzZpHqNkGgHaCvThSgGvTlUkYsGgKcTzGkAlMhYpQwDwHp");
     search.setFormName("BuDjWqAsIbHnHdSpNbTyEqOoXxHaEaYgGwJtDeBtQjIaCpVpOq");
     search.setGroupBy("ObSfNrKeLzMuPxAmZbXpClAsZvMiCtPnWaIrTyXrWlJcF");
     search.setMyKey("KcTlAyBhZzSiBzMkIjNfRcJyVxFeXgKzPyDmCuVxAqDyI");
     search.setMysql("McEmNvIbChVpQjSjXsYeXjYkVsFnYtIxAsUoTzNrSeKtDlUaXwZwLjMwIpZeJrReTjEuJtFkTqPhPdXlCeDiZmYpClSyUaRoJtVcAvPqMrPqRtJbWcZbFtNqDgYwSkYgOsTiNaYhWmBfNqEmAlQxXzRxQqSfOgKrYvZoDmNrLiGdNuDrIoNbNjUfHfPrKzBtWkEvBhMcWaLfVvDuFaPnKxPwSrMdVkWuBrLyCmKzIdPaTcUuQjFnAwKfCtDiZsBkVeMoQzLaSyJkNbGtJaJcSkTnMsRxFjNtDmCvVwQzIjGgHzLzHzElInMjQxIxKiQaMeQsBdIgQdAkOuEaCxUwLkSuVsPgDwFdHxZaQoCaPlLtMiYyHhBnRuKdKnNnRyPuKxRqWoPmUqHvUqRdHjHbFsWyWiHbLoJrZtFuAtCnCdImTrYwYkDrRnWbBbZkPwVwKdUpDmUhSsYtLeDtCkBgEzObStTsAuDrSeEfHoTnCcWcGwEvPrPcUuCaClYqKsLnCtRuAnWpIoWxTvJfKcGpWjDhBrYkPpMhRhUwDvDeVaFeOfKdBkOeEsYvHbTgJdCtQqNbMqEzGgZiUaXuLpDoSrIlVfEuFlKeLhPyKkExIlUrIhUxNyJkFkFnRsCxMsYpKsFdXdSeQuRqXrHfQxCzRcEdYsBaYhCrOgVuRqDzWrKnXvXiZoQeFxMvYjCdDzYnOtMbRhEjWuTlQmYzDzAtCfGmUtUoPnCgDbTgXpPzSsLqZpZdCgNxCcSoDdOsTjZyRfBrCnHsBoTuCqRwLkIzCyYiBbGgKrJaUjSgFsPzUdBtIkZyRtSpYoYxLgZgKvYoPjWySeUsWzZoTtLgCmCrLgMsIiDyNoNbXjFwJzXfIaGnKxUuMkTfVmUcTyVlPbAqWyEiElSoZgRvEuWoKbIxCiBgSeFvWxBwQxGdOoBfOvDbYqMhSaCdGrLnIeQmThRqNfRjWiKrYcGiOyDqBlAiXgDpLbJsQoHrIeIdAxPnEiYiSsHkXwIkAgWiJwFnAcZnSwTwOkWwUiLvKqIgRhHoFaMrSdUrAfUxHtRoRoDuInJmEzUnHnGgUwYuWmScWmRdJuOlYyScMbHpFiNjQpSoPlJkFhFiWiIsLmLaTdSkZmMlBtHaSuBoQfOqCdXmQrJoTgEyMqMnYjPsDjUoQnFeLbRuSwYfIbAcYhSpOeQvRiDcAtQqEqPeZhYnJmFcKzQtHlVrZnSeIjTlOaRpIfLjRzDlXsCgNfSqWhWcBaXxFeZuLaQwKbIgWeRmOmZzNvFqDrZbFzDeZaExXlAqByVrIwMcXzTbDbWpUlNnLuImIvSvWwCmSyRvZuWfZmOaGpDuTfNwOpViXdIcDjJsLwUqGuOvZdAoEgYpOrUoAfMoGyZsWtArNdBdDcHpVcLpLoZpUbXqUbIjLdTqMcYfBwVgWeKqFvJeOwIuXsOvQqDzLuYpOeStZeCyVsRzXxMvGrXyLbIgObUkCcPzEnZeDqRiOrOrCsQhTdSlCwKiLxFnFfDxIoAjTgTeDzQsHrBcRsVhKpWaEfGiYqJvWxSsDjOvQcEvFnEuOkCgNdXzPcCoKmQiLfLzOeMaEyCoBzDhJxQkGrQkFzRiMqHsPvPmLyGjTgDyZtDhOdAuLzTwUsOiZhIpRfFiXfLqVzGyVkOhCbInJsYiFmBcCnLcFcObCoHqSzFlEwOpYrSwQhYrZiGmWnCsEhPqRbOhMaRlMcAnQiCwIoMkHpVlAsZdCoZiHtBsAyFnQwMdDgEyBhXgAtOgHhVlUuYgVqUyMfTiSyLbEfPaUhLpSpRoQyDsXgYwFkAoRpGsZlCkJvLqLjPtLpXcUvPpAnXxCbDrAbOsYlZiDlZlAcRnTjAkIwKfAbLlLkWiPbRfEvCiKbRzYcTgXoUyQhZnLqOfNrXxOaCgRmFhWvGqOjVvFzXhFeXrLrKhYvQxPaNhFpNoGeJwYbBcYaFsNtBpPsNyGrYzTtPeIjIbCdEtYjPoCyJbOjEfJpAqMpVeRrJsWtEbQwKpNtGgSdMqGcNkKlGoCgPmVsLdVrEaUgOaHiTtGvJrQqTpRaSbHqTnBrTeEkPmVeIcGoEuMrQtNzCjBoApFlZqMiLgGdPpTrKyYgKqDhGpIyYmWpKwVpKeNuDrFxKmHnLjTqDgLyLeInJaKaEbTzCwItCqQqMiDwDxGxBdGyOzTtFxNoRoLsWsGgDxTpGeGkYzJtAaFsPpTnEmWmHtPfCzSsLzKzWlKsPmCoWgCkMlXbHqAkXeWxHjJeSqVvEmIpElYgHwRyZuQdRvAoIvVbHqHqPpDzEhRwHyObUnNyUdKeIqEbJtBqFkSvHhNtOsKrQnIzGdKbRtHwMlCpSaQxJyThPdHfLqNiPmQtOhPqDkAsYkYlMsTrOrLkXbNhMtYgHuBcHjQnDkYlWpWnQgTkOnHyTxSxGeRmUvXdCiFcEyLoOnZtZfDdXwRwJpUcRqAuPwCcXoNuMsPsWsEwBxFqVhPcReJzBuOzHlDdOaRmRmYqMvMdWrNhPbByKgGjXvRjSbLrVqFlMiQsPtOpZeZrXnElOsCyKfArWdXsLyKjTyXvZbOoVbZrVzSbXoLsYtSvSlSpKwDvUyLhCrZaMsSuPoDtEdApWcBmRiJxUcQrXzOaNaEwGkBsAoNcYoEgTcJkRpYqLfYbDoBfUyNtBsGdWyXvFiNfKtGjLmTsInAmIlSwAiPrKbHuSdAmZgDhSgWyVvCnRuYaKbVaMsXoNqHvXzXkGtOfIhQcRpHyToHcYoGuTjGePiCfWcByCcPlUsEnRpWrRgXdWnFzPkGgMjFsMfYzCcQhSfIjTlMhPfXuPpXuSeDaJpDxAdHoBfBjOnRmJxFjCeThGrDvFbTsEsOkYqFvVlFcHrCmGeCaStUxGbYkTkSmOaFnKsAlNzZsNqRkNvClXnZwZgYyKtDpVxTbLfUvYsMhUaZlUpSaEyVmBhQsPcIzNqWhClSzEiFdDiFxRtAhKzPlIkXyFySnTwUkBgFkNgBkZdCrMnIqOnSkQrCaEwDhIbYwFkTkVfYaBrQoFwVsNkOxMfYxYaOpNqVmZxIkNyOtXuHeXjZrDoKhCgYzQjNjVrIgBvAwRyEpGvIwUpIyUhPfTyDzDoNtCuXuPkTbSwFiZdPdJlPeXaZfHxUiPsXeVeOvGeOjMsKpDnHaEzXjUaSkVnPnAuThYzNzUpRuYqRtFbCbAiKjWwCuXyAyHwIqJxOzWtIpOvGkUjTbPaCoYkYkSyZwJzIaIcJvZiLhJsPbHrMpAiVrBtWaRmNrRbCqQgFkSzUvBhGwCnAnXeNeZaCyDtEiVyAaIwYfGvGeMxGuUoTnQxXnVjIeNrDePeMsKbBpHaMxEdIcVsZlSsFwYqDqMgYyBhTrBeGwRcSeIvEtGiUkNzEeXsEuQkLzAeJgYdYbCxVbBsRnWzSiKeMdHqCpDbRrUyNkUnKnHjRvQbXyMzDvTnDvSqKlUlLhAoYbImRcVcRwHkCuKwJaNrMgGlQpLoWyCmVtFjHmHmRmBwRoNhOcAtBjFeYtJaEwFqGpPxRsHyAeWqZnByNoUkYfUwRvBdYvMpLgLoGxGiVcDlWtBeTfVqMiJzKfMdIaPbXpTdPmWwQxIpTkXeBbGbToVnDxAtVwCmBfGtUjIcGkTgWpGgZsRjAuFuRfIzYmXdVgCqCpLbUbYoRaWiVuNcRjNgLqWeOyVfXtGvAbGyXlYpQdEaSsAqZiXsMvDjCgSiTwJpJqQsSsYeIrSjCwViWeCoLcVqEeMeKrYhQmNeDuIzKbWmHrRcYvZrFuLcMpQoZxRpVnZjMpQaKlEwLiHdUtLzRkAyZyZmYhArHkUvJiDiGsKkQjVvMmNxNjEnDyKrAwAyVkCnPjLxJyHkHxAbPdVmMrMdPqKjHnLwJvPvTdKsWaEvVuFqWpFgWhWqBrCyGeDbHpSvOhHjAkJaNcEcYmMxGaNsJsHoNpPrSyZtWkDmCjBkTaJoPqQpJqVvXeEgNcUyInAsQhMzFjHpHwIdRyIhJfSdDkRvMaJdCtIwIjJvSpLtXgPfEaHjHsEbOsVrWrYnWlRnKrFwMvOeLsLjJrMlRvChTxJcQoOwDkOuKhMdYrMbWmHePcWsTbEhVfYtEqVzKqAfPfHaUwMoNmBqYrFdIbIrZaZgKbTpPrNvUeGjIwEgAqAmHxIeLgFbGiKdUeFkQbGmNyRuAvKnAjPzPqFrEpYbXeEdDlOmLeUhEvAmDnSnIjTxMiAyGvDqMhFrFaLyCjOkVeLdTaUgIsIwCyQgRqHrSiSiSlXqEeCbXrVyCzJuTzWoBuAhWiFsDvNaRiTjSwEtHhYeXtHyHyOtTpJiMqXwJwTeYsBhSjKvRuSxFlVaChLbBeBaKxMmKxXbYkEkQhUhEqBrJeEyWpYjWzDbYiOgFoYpQqSlUbAqDrQwGyHpQqKcLzWsGoTiQaQfWwZdWtLjEoFdRgDiSzKeMxQsBpLfPjNdWeKgZtUgQeVyJiRvSrPvTuEkOvWcEpOvZjQlUuVfYgRnQnTfAjNwZmTcUkHkPjOqVxJeAhIlTmWfXxRhKkBeSqZtXvSoUkLsKoZmYaJkSpQoAdMgZqNnUzPwZrOaRuBkPvXsOsYpByUgAqAhGyZkWpQoAzRrMaBlDaOxPhMeAdJzEuUyOjNiBtVaYfQhIsEwLhMqYbBzTbKoFvOeUmDjHuDcJcJgDbMvAeOjLjOxJzJgTnNdEsQtGfThAnWuReGuWzUlTjGgGfHtCgMvKgVzGhBsWhFcAyYeHbZaJbJoUrPsGqSiEdDzVqHpIwWaDxDtZqArKqJrYwZfCvKbRkCrWdXyPsGqStIxEmAtXzZzPeNbWsBgRqQmXdNiLdOoGkFpIfBmZnUuTeEkZrOyKvZrRyDcGoPcNgCwRqZtYkAiBqIuXjYzEiHgXnKuZrJuCrPrLnMxSnMpWcWfNyZhYeKpKfKrZbIeFsOrAhMuOjVqZkDpPgNqEoVfGgItIeKyAgImOjUgVqEcIcNlJtQdCsSrNxSsAfWd");
     search.setOrderBy("TyZdQlTrKkRyIaAtSzCqWtTuYiXqDrPuLcKwHhPsXlQpU");
     search.setPageSize(7.19868859298996E8L);
     search.setSearchName("EeIdMxOdNeAlNfGvWpVzTwKlQrOpSzZvGmGzAeTfQbHeLbFnVz");
     search.setTitle("IjDpEoVnYvPfBhRfLxXbVuZaYtYoAjTnOeOiTsTwEgKjKgNmAjYoJhBkOoYhBbDiWnDqLbRmOeDhUxSj");

     action.setSearch(search);

     assertEquals("input", action.save());
     assertFalse(action.hasActionErrors());
     assertFalse(action.hasFieldErrors());
     assertNotNull(request.getSession().getAttribute("messages"));
     }

     @Test
     public void testRemove() throws Exception {
     MockHttpServletRequest request = new MockHttpServletRequest();
     ServletActionContext.setRequest(request);
     action.setDelete("");
     Search search = new Search();
     search.setSearchId(-2L);
     action.setSearch(search);
     assertEquals("success", action.delete());
     assertNotNull(request.getSession().getAttribute("messages"));
     }*/
    @Test
    public void testDummy() {
        this.log.debug( "SearchActionTest" );
    }
}